spring:
  profiles:
    active: dev
  application:
    name: ADX-CLOCKWORK-WEB

server.port: 9006

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 5000

ribbon.eureka.enable: true

